name: iPerf Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Example schedule to run every day at noon

jobs:
  iperf:
    runs-on: ubuntu-latest

    steps:
      - name: Install iPerf
        run: sudo apt-get update && sudo apt-get install -y iperf3

      - name: Run iPerf Server
        run: iperf3 -s &
        
      # Example of how to run a client test (adjust as needed for your use case)
      - name: Run iPerf Client
        run: iperf3 -c localhost -t 10
