name: Speed Test

on:
  workflow_dispatch:  # Allows manual trigger from GitHub Actions UI

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: Install Speedtest CLI
        run: sudo apt-get update && sudo apt-get install -y speedtest-cli

      - name: Run Speed Test
        run: speedtest-cli
