name: Speed Test

on:
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * *'  # Optional: Schedule to run every day at noon UTC

jobs:
  speedtest:
    runs-on: ubuntu-latest

    steps:
      - name: Install Speedtest CLI
        run: sudo apt-get update && sudo apt-get install -y speedtest-cli

      - name: Run Speed Test
        run: speedtest-cli
